name: .NET Workflow CI/CD

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # Executa a cada hora

jobs:
  push-job:             # é acionado pelo evento de push
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run build
      run: echo "Building project on push..."

    - name: Run tests
      run: echo "Running tests on push..."

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
          dotnet-version: '8.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal

  cron-job:             # é acionado pelo agendamento
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Execute scheduled task
      run: echo "Running scheduled task every hour..."
